version: '3'
services:
  portainer:
    image: "portainer/portainer:arm"
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - /var/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: portainer

  influxdb:
    image: "hypriot/rpi-influxdb:1.2.2"
    restart: unless-stopped
    ports:
      - "8086:8086"
    volumes:
      - /media/usb/influxdb:/data
      - ./config/influxdb.conf:/etc/influxdb/influxdb.conf
    environment:
      - ADMIN_USER=root
      - INFLUXDB_INIT_PWD=root
      - PRE_CREATE_DB=smarthome
    container_name: influxdb

  grafana:
    image: "fg2it/grafana-armhf:v4.6.3"
    restart: unless-stopped
    ports:
      - "3000:3000"
    links:
      - influxdb
    volumes:
      - /var/grafana:/var/lib/grafana
      - /var/log/grafana:/var/log/grafana
      - ./config/grafana.ini:/etc/grafana/grafana.ini
    container_name: grafana
  nodered:
    build: build
    image: elzekool/rpi-nodered
    ports:
        - "1880:1880"
    volumes:
        - "${PWD}/data:/root/.node-red"
    privileged: true
    restart: "unless-stopped"
