version: "3"
services:
  portainer:
    image: "portainer/portainer:arm"
    restart: always
    command: --admin-password "$$2y$$05$$1rp2t2s2/E/3E.LHKjTAlewxX3NZeEqxtB58Dc8AWAYkSvXCcPJMm"
    ports:
      - "9000:9000"
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: portainer

  influxdb:
    image: "hypriot/rpi-influxdb:1.2.2"
    restart: always
    ports:
      - "8086:8086"
    volumes:
      - /media/usb/influxdb:/data
      - ./config/influxdb.conf:/etc/influxdb/influxdb.conf
    environment:
      - ADMIN_USER=root
      - INFLUXDB_INIT_PWD=root
      - PRE_CREATE_DB=smarthome
    container_name: influxdb

  grafana:
    image: "fg2it/grafana-armhf:v4.6.3"
    restart: always
    ports:
      - "3000:3000"
    links:
      - influxdb
    volumes:
      - /var/grafana:/var/lib/grafana
      - /var/log/grafana:/var/log/grafana
      - ./config/grafana.ini:/etc/grafana/grafana.ini
    container_name: grafana

  sp108e:
    build: "sp108e"
    restart: always
    ports:
      - "13000:3000"
    container_name: sp108e
    environment:
      - SP108E_IP=${SP108E_IP}
      - SP108E_PORT=${SP108E_PORT}

  mi_home:
    build: "mi-home"
    restart: always
    ports:
      - "14000:4000"
    container_name: mi_home
    environment:
      - ROBOROCK_IP=${ROBOROCK_IP}
      - ROBOROCK_TOKEN=${ROBOROCK_TOKEN} 

volumes:
  portainer_data:
